# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = xrandr --output DP-2 --primary
exec-once = [workspace 2 silent] firefox
exec-once = [workspace 3 silent] discord
exec-once = openrgb --server
exec-once = sleep 10 && ~/.local/bin/personal_openrgb_set_colors
