windowrule = rounding 4, match:float 1
# Overrides default floating window size to be larger to accommodate larger default font size
windowrule = tag -floating-window, float on, size 1280 780, center on, match:class ^(org\.omarchy\.fastfetch-tui|org\.omarchy\.btop|com\.gabm\.satty)$
